### ISSUE TITLE
Is it ready?

### ISSUE THREAD

**Issue by wisefool769** [aido/app-seed-tool#4]
Hey! Is this app ready for prime-time? Do you have installation instructions?

**Comment by aido** [comment]
Hi @wisefool769

See more detailed reponse here: https://github.com/LedgerHQ/ledger-nano-s/issues/54#issuecomment-1536900948

Also have a GitHub discussions page here: https://github.com/aido/app-sskr-check/discussions

I've never used GitHub discussions before so we'll see how it goes. May be good for general queries that aren't issues.
