### ISSUE TITLE
v1.3.2 Check SSKR recovery phrase "Restart from word #" is broken

### ISSUE THREAD

**Issue by InfiniteQE** [aido/app-seed-tool#9]
I also found 3 bugs, testing a SSKR recovery on NanoS (restored with the mnemonic below)

I compiled seedtool-cli, then
`$ seedtool --in bip39 all all all all all all all all all all all all --out hex`
`$ seedtool --in hex --out sskr --group 2-of-3 0660cc198330660cc198330660cc1983

`tuna acid epic gyro fair chef able acid able very flap jazz fizz judo omit dull drop inch body join zinc luck crux pool puff jugs cola meow yoga`

`tuna acid epic gyro fair chef able acid acid ugly what flux days very urge memo news fact jowl hope luck jump urge beta veto gush days judo each`

`tuna acid epic gyro fair chef able acid also mild exit easy luck gala hawk girl gush ugly wave axis cost jade slot yank bulb zero knob next liar`

1st attempt :
Entering a 2of3 scheme, I think I missed a word, so I went to "Restart from word #20", however the word entry counter didn't decrease to the restart word#.

Selecting the "Restart from word # 1" resulted in app SSKR Check freezing.

2nd attempt :
I made a selection mistake on word #28, missed the restart, and ended up in word #29 entry.  Scrolling right from the confirm byteword entry in #29, it only lets me restart from #24 and below, I can't restart from #28.  Selecting restart from #24 the app still says "Enter Share#1 Word#29".  

Entering here my 24th word here results in `SSKR Check` moving on to "Enter Share#2 Word#1"

Issues : 
- Restart from word # doesn't work
- Making a error is hard to fix, if I accidentally selected the wrong byteword for #28, when entering #29 it would be nice for there to always be a backspace added to the alphabet entry, if the user chose backspace on the 1st letter of a given word, it should go back to entry of the prior word.

**Comment by InfiniteQE** [comment]
I've deleted v1.3.2 with ledgerblue, and installed my debian VM built v1.4.0 (from cloning the latest github repo)

- Running Enter SSKR recovery phrase -> Enter Share#1 Word#...6, I chose Restart from word # 1  -> App freezes
- Regarding the "backspace" option, it is only in the alphabet from the 2nd letter entry of a byteword, it would be ideal if it were there from the 1st character entry, and by selecting it, it would go backwards to the word prior

- I spent ages entering SSKR share # 1 and # 2 in my NanoS, only for it to say invalid.  It would be ideal if the user could go back and review which bytewords were entered to determine which word is incorrect, rather than having to start all over from scratch

- Do SSKR shares have a checksum ? And if so does your app check them ? Most likely I entered a byteword incorrectly but if would be bad luck if I entered 1 word of a share wrong yet still had a valid checksum.

**Comment by aido** [comment]
Hi @InfiniteQE,

I agree that the app SSKR Check needs a bit more 'polish' when dealing with situations where users enter incorrect phrases. Most of the testing to date was to ensure that when a user enters correct input the app generates valid SSKR byte words. This is critical so that users do not lose funds. The functionality and tests for when a user enters incorrect phrases is a bit clunky at the moment but should still be usable.

My defensive logic is that if a user is being serious about protecting their funds they will then take the time to make sure they are typing the correct phrases. :-)

Also, adding extra functionality could be tricky as the size of the app is almost at the limit of a Nano S.
